# ─────────────────────────────────────────────────────────────────────────────
# AVISO: arquivo originalmente gerado por pyuic6 a partir de um .ui que não
# está mais acessível. Agora é editado À MÃO e é source-of-truth da janela
# de Opções.
# NÃO REGENERAR com pyuic6 — perderia todas as customizações
# (i18n pt-BR, presets de cache, tab Integrações, etc.).
# ─────────────────────────────────────────────────────────────────────────────


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog.resize(583, 234)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbCacheAndDatabase = QtWidgets.QGroupBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbCacheAndDatabase.sizePolicy().hasHeightForWidth())
        self.gbCacheAndDatabase.setSizePolicy(sizePolicy)
        self.gbCacheAndDatabase.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.gbCacheAndDatabase.setObjectName("gbCacheAndDatabase")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbCacheAndDatabase)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.gbCacheAndDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_cache_expiration = QtWidgets.QComboBox(parent=self.gbCacheAndDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_cache_expiration.sizePolicy().hasHeightForWidth())
        self.cb_cache_expiration.setSizePolicy(sizePolicy)
        self.cb_cache_expiration.setObjectName("cb_cache_expiration")
        # Items are populated dynamically in options.py via addItem(label, userData)
        self.horizontalLayout.addWidget(self.cb_cache_expiration)
        self.horizontalLayout.addStretch()
        self.verticalLayout_2.addWidget(self.gbCacheAndDatabase)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.le_DownloadPath = QtWidgets.QLineEdit(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_DownloadPath.sizePolicy().hasHeightForWidth())
        self.le_DownloadPath.setSizePolicy(sizePolicy)
        self.le_DownloadPath.setObjectName("le_DownloadPath")
        self.horizontalLayout_2.addWidget(self.le_DownloadPath)
        self.pb_BrowsePath = QtWidgets.QPushButton(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_BrowsePath.sizePolicy().hasHeightForWidth())
        self.pb_BrowsePath.setSizePolicy(sizePolicy)
        self.pb_BrowsePath.setObjectName("pb_BrowsePath")
        self.horizontalLayout_2.addWidget(self.pb_BrowsePath)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_unzip = QtWidgets.QCheckBox(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_unzip.sizePolicy().hasHeightForWidth())
        self.cb_unzip.setSizePolicy(sizePolicy)
        self.cb_unzip.setObjectName("cb_unzip")
        self.horizontalLayout_3.addWidget(self.cb_unzip)
        self.cb_checkupdates = QtWidgets.QCheckBox(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_checkupdates.sizePolicy().hasHeightForWidth())
        self.cb_checkupdates.setSizePolicy(sizePolicy)
        self.cb_checkupdates.setAutoFillBackground(True)
        self.cb_checkupdates.setObjectName("cb_checkupdates")
        self.horizontalLayout_3.addWidget(self.cb_checkupdates)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignBottom)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configurações"))
        self.gbCacheAndDatabase.setTitle(_translate("Dialog", "Cache e biblioteca"))
        self.label.setText(_translate("Dialog", "Atualizar catálogo a cada (dias)"))
        # cb_cache_expiration items são populados dinamicamente em options.py com userData
        self.groupBox_3.setTitle(_translate("Dialog", "Pasta de download"))
        self.label_3.setText(_translate("Dialog", "Pasta de download"))
        self.pb_BrowsePath.setText(_translate("Dialog", "Escolher…"))
        self.groupBox_2.setTitle(_translate("Dialog", "Comportamento"))
        self.cb_unzip.setText(_translate("Dialog", "Descompactar após baixar"))
        self.cb_checkupdates.setText(_translate("Dialog", "Buscar atualizações ao iniciar"))
